=== specsie/foundation/schema.json
{
    "type": "object", 
    "$schema": "http://json-schema.org/draft-03/schema", 
    "id": "http://specsy.net/schema/foundation", 
    "required": true, 
    "properties": {
        "constraints": {
            "type": "array", 
            "id": "https://specsy.net/schema/foundation/constraints", 
            "required": true, 
            "items": {
                "type": "object", 
                "id": "https://specsy.net/schema/foundation/constraints/0", 
                "required": true, 
                "properties": {
                    "constraint": {
                        "type": "string", 
                        "id": "https://specsy.net/schema/foundation/constraints/0/constraint", 
                        "required": false
                    }
                }
            }
        }, 
        "description": {
            "type": "array", 
            "id": "https://specsy.net/schema/foundation/description", 
            "required": true, 
            "items": {
                "type": "string", 
                "id": "https://specsy.net/schema/foundation/description/0", 
                "required": false
            }
        }, 
        "includes": {
            "type": "array", 
            "id": "https://specsy.net/schema/foundation/includes", 
            "required": true, 
            "items": {
                "type": "string", 
                "id": "https://specsy.net/schema/foundation/includes/0", 
                "required": false
            }
        }, 
        "inherits": {
            "type": "object", 
            "id": "https://specsy.net/schema/foundation/inherits", 
            "required": true, 
            "properties": {
                "spec": {
                    "type": "string", 
                    "id": "https://specsy.net/schema/foundation/inherits/spec", 
                    "required": true
                }, 
                "baseline": {
                    "type": "string", 
                    "id": "https://specsy.net/schema/foundation/inherits/baseline", 
                    "required": false
                }
            }
        }, 
        "json-schema": {
            "type": "array", 
            "id": "https://specsy.net/schema/foundation/json-schema", 
            "required": false, 
            "items": {
                "type": "string", 
                "id": "https://specsy.net/schema/foundation/json-schema/0", 
                "required": false
            }
        }, 
        "spec": {
            "type": "string", 
            "id": "https://specsy.net/schema/foundation/spec", 
            "required": false
        }
    }
}

=== specsie/foundation/specdoc.json
{
    "json-schema": [
        "/schema.json"
    ], 
    "includes": [
        "/specdoc.json"
    ], 
    "inherits": {
    }, 
    "spec": "", 
    "constraints": [
        {
            "constraint": "The key words 'MUST', 'MUST NOT', 'REQUIRED', 'SHALL', 'SHALL NOT', 'SHOULD', 'SHOULD NOT', 'RECOMMENDED',  'MAY', and  'OPTIONAL' in this spec are to be interpreted as described in RFC 2119."
        },
        {
            "constraint": "Every included specdoc MUST be valid in respect of every specified json-schema."
        }
    ], 
    "description": [
        ""
    ]
 
}
